/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionBar: typeof import('./src/components/ActionBar/index.vue')['default']
    Attachment: typeof import('./src/components/Attachment/index.vue')['default']
    AttachmentFilePreview: typeof import('./src/components/AttachmentFilePreview/index.vue')['default']
    Editor: typeof import('./src/components/Editor/index.vue')['default']
    EmailCell: typeof import('./src/components/EmailCell/index.vue')['default']
    EmailList: typeof import('./src/components/EmailList/index.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    InputTagField: typeof import('./src/components/InputTagField/index.vue')['default']
    Navigator: typeof import('./src/components/Navigator/index.vue')['default']
    NewMailSheet: typeof import('./src/components/NewMailSheet/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Segmented: typeof import('./src/components/Segmented/index.vue')['default']
    TextButton: typeof import('./src/components/TextButton/index.vue')['default']
    VanActionBar: typeof import('vant/es')['ActionBar']
    VanBackTop: typeof import('vant/es')['BackTop']
    VanBadge: typeof import('vant/es')['Badge']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanDialog: typeof import('vant/es')['Dialog']
    VanDivider: typeof import('vant/es')['Divider']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSearch: typeof import('vant/es')['Search']
    VanSpace: typeof import('vant/es')['Space']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanTag: typeof import('vant/es')['Tag']
    VanTextEllipsis: typeof import('vant/es')['TextEllipsis']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
